### ISSUE TITLE
Incomplete line

### ISSUE THREAD

**Issue by Halfwalker** [Logvin/synctorrents#1]
https://github.com/Logvin/synctorrents/blob/23d617feb27bab39fb7d7a73f1725403d139e17e/MoveCompleted.sh#L146

Looks like an incomplete line.  Possibly copy/pasta from a terminal screen ?  Ends with

`.... $DIR"/"$fileName" && rm "$fullE$`

where it should likely be

`.... $DIR"/"$fileName" && rm "$fullExtractedPath ....`

**Comment by Logvin** [comment]
I completely re-wrote the script, feel free to check it out.
